spring:
  application:
    name: crudrestapp
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml
  default-schema: postgres

server:
  port: 8000
  error:
    include-message: always

rsa:
  privateKey: classpath:certs/private-key.pem
  publicKey: classpath:certs/public-key.pem

logging:
  level:
    org:
      springframework: INFO